services:
  postgres:
    image: postgres:17-alpine
    container_name: lapaksoed-postgres
    environment:
      POSTGRES_DB: lapaksoed
      POSTGRES_USER: lapaksoed
      POSTGRES_PASSWORD: lapaksoed
    ports:
      - "5432:5432"
    volumes:
      - lapaksoed-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lapaksoed -d lapaksoed"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  lapaksoed-postgres-data: